apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 2d58ef80b735dbb32a59d1daac8d0f1e56a3df15
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad4-meme-generator-backend
  labels:
    app.kubernetes.io/instance: squad4-meme-generator-backend
    app.kubernetes.io/name: squad4-meme-generator-backend
  name: squad4-meme-generator-backend-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: squad4-meme-generator-backend
    app.kubernetes.io/name: squad4-meme-generator-backend
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 2d58ef80b735dbb32a59d1daac8d0f1e56a3df15
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad4-meme-generator-backend
  labels:
    app.kubernetes.io/instance: squad4-meme-generator-backend
    app.kubernetes.io/name: squad4-meme-generator-backend
  name: squad4-meme-generator-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: squad4-meme-generator-backend
      app.kubernetes.io/name: squad4-meme-generator-backend
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 2d58ef80b735dbb32a59d1daac8d0f1e56a3df15
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad4-meme-generator-backend
      labels:
        app.kubernetes.io/instance: squad4-meme-generator-backend
        app.kubernetes.io/name: squad4-meme-generator-backend
    spec:
      containers:
      - image: quay.io/levandrejev/squad4-meme-generator-backend:2d58ef80b735dbb32a59d1daac8d0f1e56a3df15
        name: squad4-meme-generator-backend
